# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\t\"4\n\x0b\x42ookingData\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x15\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x06.Dates\"%\n\x05\x44\x61tes\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"?\n\x0eNewBookingData\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07movieid\x18\x03 \x01(\t\"\x0b\n\tEmptyData2\x8d\x01\n\x07\x42ooking\x12)\n\x12GetBookingByUserID\x12\x03.Id\x1a\x0c.BookingData\"\x00\x12+\n\x0bGetBookings\x12\n.EmptyData\x1a\x0c.BookingData\"\x00\x30\x01\x12*\n\x10\x41\x64\x64\x42ookingByUser\x12\x0f.NewBookingData\x1a\x03.Id\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ID']._serialized_start=17
  _globals['_ID']._serialized_end=33
  _globals['_BOOKINGDATA']._serialized_start=35
  _globals['_BOOKINGDATA']._serialized_end=87
  _globals['_DATES']._serialized_start=89
  _globals['_DATES']._serialized_end=126
  _globals['_NEWBOOKINGDATA']._serialized_start=128
  _globals['_NEWBOOKINGDATA']._serialized_end=191
  _globals['_EMPTYDATA']._serialized_start=193
  _globals['_EMPTYDATA']._serialized_end=204
  _globals['_BOOKING']._serialized_start=207
  _globals['_BOOKING']._serialized_end=348
# @@protoc_insertion_point(module_scope)
